# Streamlit configuration
[theme]
primaryColor = "#0066CC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EFEFEF"
textColor = "#000000"
font = "sans serif"

[client]
showSidebarNavigation = true

[server]
headless = true
enableCORS = false
port = 8501
